
import type { NextPage } from 'next';
import Head from 'next/head';
import { NexusNavbar } from '../components/nexus-navbar';
import { NexusHome } from '../mypages/nexus-home';
import { NexusFooter } from '../components/nexus-footer';

const Home: NextPage = () => {
  return (
    <div style={{backgroundColor: " #121724"}}>
      <Head>
        <title>Nexus Crypto Casino</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
        <NexusNavbar />
        <NexusHome />
        <NexusFooter />
    </div>
  );
};

export default Home;
